### ISSUE TITLE
Latest master fails to compile

### ISSUE THREAD

**Issue by tomgross** [OfficeDev/msteams-meetings-template#18]
The latest master (ce09f9976a633c8dc3e80ddc7b9835dfef73323d) fails to compile (on `yarn start`)

```javascript
Failed to compile.

/Users/macbookpro/VC/msteams-meetings-template/src/RootReducer.ts
TypeScript error in /Users/macbookpro/VC/msteams-meetings-template/src/RootReducer.ts(9,27):
Namespace '"/Users/macbookpro/VC/msteams-meetings-template/node_modules/@types/history/index".History' has no exported member 'PoorMansUnknown'.  TS2694

     7 | export interface AppState {
     8 |   meeting: MeetingState;
  >  9 |   router: History<History.PoorMansUnknown>;
       |                           ^
    10 | }
    11 |
    12 | export function createRootReducer(history: History) {
```

My system:
- Mac OS 10.15.6
- node 14.12.0
- yarn 1.22.5

**Comment by timrobinson33** [comment]
I hit this problem in my own code recently. If you have access to the source you can fix it by changing:

`router: History<History.PoorMansUnknown>;`

to:

`router: History<unknown>;`

It seems that PoorMansUnknown has been removed in a recent update to something (I'm not quite sure where it was defined). From the discussion here https://stackoverflow.com/questions/60768879 it looks like it was for backwards compatibility with old versions of TypeScript that are no longer supported.

**Comment by aosolis** [comment]
Thanks for the report-- this is now fixed.
