### ISSUE TITLE
apis for teams meetings

### ISSUE THREAD

**Issue by moblizeit** [OfficeDev/msteams-meetings-template#20]
we use angular and nodejs. Not familier with react. is there a place where i can see the REST apis required to create the meeting? could not find that part of code in the sample as i am not familiar with react

**Comment by RobPethick** [comment]
The rest API details for online meetings are here: 
https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0

**Comment by RobPethick** [comment]
The file where they are called in this project are here:
https://github.com/OfficeDev/msteams-meetings-template/blob/master/src/meeting-creator/service.ts

**Comment by aosolis** [comment]
@RobPethick was spot on-- thank you!

For completeness, there's also the Create event API for creating an event in the user's calendar, which you can call in a way that creates an event with an online meeting:
https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=http#example-2-create-and-enable-an-event-as-an-online-meeting
